# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\'\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"8\n\x14RegisterUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"7\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x13ListMessagesRequest2T\n\x0bUserService\x12\x45\n\x0cRegisterUser\x12\x19.chat.RegisterUserRequest\x1a\x1a.chat.RegisterUserResponse2\x85\x01\n\x0eMessageService\x12\x37\n\x0bSendMessage\x12\r.chat.Message\x1a\x19.chat.SendMessageResponse\x12:\n\x0cListMessages\x12\x19.chat.ListMessagesRequest\x1a\r.chat.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=20
  _globals['_REGISTERUSERREQUEST']._serialized_end=59
  _globals['_REGISTERUSERRESPONSE']._serialized_start=61
  _globals['_REGISTERUSERRESPONSE']._serialized_end=117
  _globals['_MESSAGE']._serialized_start=119
  _globals['_MESSAGE']._serialized_end=180
  _globals['_SENDMESSAGERESPONSE']._serialized_start=182
  _globals['_SENDMESSAGERESPONSE']._serialized_end=237
  _globals['_LISTMESSAGESREQUEST']._serialized_start=239
  _globals['_LISTMESSAGESREQUEST']._serialized_end=260
  _globals['_USERSERVICE']._serialized_start=262
  _globals['_USERSERVICE']._serialized_end=346
  _globals['_MESSAGESERVICE']._serialized_start=349
  _globals['_MESSAGESERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
