# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x1b\n\x0c\x43ountRequest\x12\x0b\n\x03max\x18\x01 \x01(\x05\"\x1f\n\rCountResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32O\n\rStreamService\x12>\n\x07\x43ountTo\x12\x17.streaming.CountRequest\x1a\x18.streaming.CountResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTREQUEST']._serialized_start=30
  _globals['_COUNTREQUEST']._serialized_end=57
  _globals['_COUNTRESPONSE']._serialized_start=59
  _globals['_COUNTRESPONSE']._serialized_end=90
  _globals['_STREAMSERVICE']._serialized_start=92
  _globals['_STREAMSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
