# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crypto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'crypto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63rypto.proto\x12\x06\x63rypto\"0\n\x0e\x45ncryptRequest\x12\x11\n\tplaintext\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"%\n\x0f\x45ncryptResponse\x12\x12\n\nciphertext\x18\x01 \x01(\t\"1\n\x0e\x44\x65\x63ryptRequest\x12\x12\n\nciphertext\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"$\n\x0f\x44\x65\x63ryptResponse\x12\x11\n\tplaintext\x18\x01 \x01(\t2\x87\x01\n\rCryptoService\x12:\n\x07\x45ncrypt\x12\x16.crypto.EncryptRequest\x1a\x17.crypto.EncryptResponse\x12:\n\x07\x44\x65\x63rypt\x12\x16.crypto.DecryptRequest\x1a\x17.crypto.DecryptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crypto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTREQUEST']._serialized_start=24
  _globals['_ENCRYPTREQUEST']._serialized_end=72
  _globals['_ENCRYPTRESPONSE']._serialized_start=74
  _globals['_ENCRYPTRESPONSE']._serialized_end=111
  _globals['_DECRYPTREQUEST']._serialized_start=113
  _globals['_DECRYPTREQUEST']._serialized_end=162
  _globals['_DECRYPTRESPONSE']._serialized_start=164
  _globals['_DECRYPTRESPONSE']._serialized_end=200
  _globals['_CRYPTOSERVICE']._serialized_start=203
  _globals['_CRYPTOSERVICE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
