# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'client_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient_streaming.proto\x12\tstreaming\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bSumResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x32I\n\rStreamService\x12\x38\n\tSumStream\x12\x11.streaming.Number\x1a\x16.streaming.SumResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBER']._serialized_start=37
  _globals['_NUMBER']._serialized_end=60
  _globals['_SUMRESPONSE']._serialized_start=62
  _globals['_SUMRESPONSE']._serialized_end=90
  _globals['_STREAMSERVICE']._serialized_start=92
  _globals['_STREAMSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
